parameters:
    snowio_connector.job.job_parameters.constraint_collection_provider.product.class: Snowio\Bundle\CsvConnectorBundle\Job\JobParameters\ConstraintCollectionProvider\ProductConstraint

services:
    # Validation constraints for our JobParameters
    snowio_connector.job.job_parameters.constraint_collection_provider.full_published_export:
          class: '%snowio_connector.job.job_parameters.constraint_collection_provider.product.class%'
          arguments:
              - '@pim_connector.job.job_parameters.constraint_collection_provider.simple_csv_export'
              - ['full_published_export']
          tags:
              - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
