services:
    # Overwrite service definition to set step name (arg 0) and writer
    snowio_connector.step.csv_published_product.export:
        class: '%pim_connector.step.item_step.class%'
        parent: 'pimee_workflow.step.csv_published_product.export'
        arguments:
            index_0: 'product'
            index_5: '@snowio_connector.writer.file.csv_product'